### ISSUE TITLE
Why is there no webdriver.xpi for firefox?

### ISSUE THREAD

**Issue by Govinda-Fichtner** [sztupy/selenium-webdriver#1]
I tried this fork of selenium-webdriver because I have a lot of problems with Chrome hanging/timeouts similar to https://github.com/jnicklas/capybara/issues/1035#issuecomment-17340620
When I use firefox it complains about a missing webdriver.xpi and indeed it is not there. Compared to https://github.com/goinstant/ruby-selenium-webdriver it seems to be missing. 
Is this intentional?

**Comment by sztupy** [comment]
This fork is from the original sources, but filtered for the rb directory (the complete source is too huge). It seems however that file is put there via another build script, that is not present in the rb directory. 

Will fix this when I have the time. (Until that feel free to fork and put the missing file there)

**Comment by Govinda-Fichtner** [comment]
Thanks for the reply. For the time being I am going to switch the firefox scenarios to chrome. 
I have another problem regarding profile settings that previously I could do like:

´´´
  profile = ::Selenium::WebDriver::Chrome::Profile.new
  profile["download.default_directory"] = DownloadHelpers::PATH.to_s
  profile['browser.window_placement.top'] = 0
  profile['browser.window_placement.left'] = 0
  profile['browser.window_placement.right'] = 1400
  profile['browser.window_placement.bottom'] = 1000
  profile['browser.window_placement.maximized'] = true
´´´

Now I get the following error:
´´´
 unknown error: unrecognized chrome option: profile
´´´

Do you know how one is supposed to provide the options now?
Regarding the size I changed to command line arguments but for the download directory there seems to be no switch...

Cheers

**Comment by sztupy** [comment]
Profile settings have changed inside chromedriver2. Here is an SO post about how to do it: http://stackoverflow.com/questions/16328801/define-download-directory-for-chromedriver-selenium-with-python/16342256#16342256

There is a prefs: parameter you can use to pass in the new kinds of preference parameters

**Comment by Govinda-Fichtner** [comment]
OK. Got it working. Would you consider your fork as stable or is it more of a hack?
It seems as if chromedriver 2 solves my problems with hanging chrome instances... while not changing my cucumber/capybara/selenium tests...

**Comment by Govinda-Fichtner** [comment]
One thing I forgot was that I got this error:
unknown error: unrecognized chrome option: detach

I had to remove 

```
detach                      = opts.delete(:detach)
```

in:

```
https://github.com/sztupy/selenium-webdriver/blob/webdriver-only/lib/selenium/webdriver/chrome/bridge.rb
```

to make it work

**Comment by sztupy** [comment]
Check that line

```
chrome_options['detach']                   = detach.nil? || !!detach  unless detach == :unspecified
```

so if you use `:detach => :unspecified` inside your intializer, it won't send that line to the driver

**Comment by sztupy** [comment]
I've already raised a bugreport on seleniums site, hopefully they'll add the nescessary features to upstream for chromedriver2 to work. The prefs handling is stable, but the way I handle the `detach` options is a bit hacky.

**Comment by Govinda-Fichtner** [comment]
Regarding chrome_options['detach'] 
I should have seen that myself... obviously I was a little fast and overlooked it...

**Comment by sztupy** [comment]
Re-added the missing files for firefox and safari. Also changed the readme, so the needed modifications should now be obvious.
