### ISSUE TITLE
Unrecognized chrome option: profile while starting Webdriver with custom profile on Chromedrive 2.2

### ISSUE THREAD

**Issue by sarosini** [sztupy/selenium-webdriver#2]
I am trying to launch chrome browser using some profile setup, but while doing that I am getting a error says "unrecognized chrome option"

This error was not happening on Chrome version 28 on older chrome driver, but recently I have updated the chrome driver V2.2 for Chrome version 29, after that I am getting this error.

I have also tried the solution suggested in this link https://github.com/sztupy/selenium-webdriver/commit/d3350b5bc6a8430cd1cfbb88912752ed79c3ad14
but nothing helped, still i am struck in the issue.

Help me to get rid of this issue!

Thanks in advance.

**Comment by sztupy** [comment]
For chromedriver v2 you cannot use the profile option when creating the driver. You are probably using it to set some options (like the download directory). You have to use prefs to set these options, and they have different semantics (that depends on what you want to achieve)
